# Generated by Django 5.1.1 on 2024-10-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_all', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_add',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
    ]
