# Generated by Django 5.1.1 on 2024-10-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_all', '0002_product_add_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_add',
            name='product_image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='product_add',
            name='product_price',
            field=models.IntegerField(default='0'),
        ),
    ]
